Initial version of the Init plugin
pestphp/pest-plugin-init pull request #1
Opened 2020-06-03 16:17 UTC by owenvoke

2020-06-03 16:28 UTC, nunomaduro requested changes

2020-06-03 16:28 UTC, nunomaduro commented on stubs/Pest.php
> +uses(PHPUnit\Framework\TestCase::class)->in(__DIR__);
Just leave an empty comment. Like this:

```
<?php

// ..
```

2020-06-03 16:28 UTC, nunomaduro commented on stubs/Helpers.php
> +<?php
Just leave an empty comment. Like this:

```
<?php

// ..
```

2020-06-03 16:28 UTC, nunomaduro commented on src/Plugin.php
> +    public function handleArguments(TestSuite $testSuite, array $originals): array
You need to have access to an output interface here. cc @fetzi

2020-06-03 16:28 UTC, nunomaduro commented on src/Plugin.php
> +            echo "Created 'tests' directory\n";
Once we have the console output, those `echo`s need to use it.

2020-06-03 16:28 UTC, nunomaduro commented on src/Plugin.php
> +                throw new \RuntimeException(sprintf('Directory "%s" was not created', $testsBaseDir));
This needs to have its own exception that needs to implement the interfaces that are on the `Pest\Exceptions` folder;

2020-06-03 16:28 UTC, nunomaduro commented on src/Plugin.php
> +        $testsBaseDir = getcwd() . '/tests';
You can use `$testSuite->rootPath` here.

2020-06-03 16:28 UTC, nunomaduro commented on src/Plugin.php
> +    private function initialisePest(): void
I would call it `init`.

2020-06-03 16:31 UTC, fetzi commented on src/Plugin.php
> +    public function handleArguments(TestSuite $testSuite, array $originals): array
Yes, will update the interface 👍

2020-06-03 16:54 UTC, owenvoke commented on src/Plugin.php
> +            echo "Created 'tests' directory\n";
Yep, was hoping we'd have that available. 👍

2020-06-03 16:57 UTC, nunomaduro commented on src/Plugin.php
> +    public function handleArguments(TestSuite $testSuite, array $originals): array
I think is better if we actually add a container on this.

Like every plugin can resolve stuff out of the container depending on what they need. What do you thinK?

2020-06-03 17:04 UTC, owenvoke commented on src/Plugin.php
> +                throw new \RuntimeException(sprintf('Directory "%s" was not created', $testsBaseDir));
Which exception would you say it should extend/implement? 🤔

2020-06-03 17:09 UTC, nunomaduro commented on src/Plugin.php
> +                throw new \RuntimeException(sprintf('Directory "%s" was not created', $testsBaseDir));
If you think that should not happen, you can use this one: https://github.com/pestphp/pest/blob/master/src/Exceptions/ShouldNotHappen.php.

2020-06-03 17:28 UTC, owenvoke commented on src/Plugin.php
> +                throw new \RuntimeException(sprintf('Directory "%s" was not created', $testsBaseDir));
I've updated this to use `ShouldNotHappen` now (it's a `final` class, so I guess this can be updated if it does need a dedicated exception class).

2020-06-05 00:07 UTC, nunomaduro commented
This is paused waiting for @fetzi work on container.

2020-06-05 22:34 UTC, owenvoke commented
One thing I need to do is update the output so it has some proper styling.

Also, I have no idea what Rector is trying to do as it seems to break the file...

2020-06-06 19:15 UTC, nunomaduro commented
Great great job. Going to test it locally before merge.

2020-06-06 19:38 UTC, merged

2020-06-06 19:38 UTC, nunomaduro commented
@fetzi @owenvoke Very good job!